@startuml

package ui {
    class SageParser
    {
        +init()
    }
}

package lib {
    class DataTable {
        -columnNames : vector<string>
        -dataRows : vector<Rows>
    }

    package Processors {
        class DataProcessorFactory
        {
            createDataProcessor(docType) : IDataTableProcessor
        }

        class IDataTableProcessor {
            +process(std::shared_ptr<DataTable>) : DataTable
        }

        class DefaultDataTableProcessor {
            +process(std::shared_ptr<DataTable>) : DataTable
        }

        class OmegaInvoiceProcessor {
            +process(std::shared_ptr<DataTable>) : DataTable
        }

        class BesuglayaInvoiceProcessor {
            +process(std::shared_ptr<DataTable>) : DataTable
        }

        note "Many other processors are not shown here" as N1
        N1 .. BesuglayaInvoiceProcessor
        N1 .. OmegaInvoiceProcessor

        DefaultDataTableProcessor -up-|> IDataTableProcessor
        BesuglayaInvoiceProcessor -up-|> DefaultDataTableProcessor
        OmegaInvoiceProcessor -up-|> DefaultDataTableProcessor
    }

    package Writers {

        class WriterFactory {
            createWriter(ReaderFileType) : IWriter
        } 

        interface IWriter {
            +setFilePath(new_path)
            +write(DataTable)
        }

        class CsvWriter {
            +setFilePath(new_path)
            +write(DataTable)
        }

        class XmlWriter {
            +setFilePath(new_path)
            +write(DataTable)
        }

        note "Many other writers not shown here" as N2
        N2 .. CsvWriter
        N2 .. XmlWriter

        CsvWriter -up-|> IWriter
        XmlWriter -up-|> IWriter
    }

    package Readers {
        class ReaderFactory {
            createReader(ReaderFileType) : IReader
        } 

        interface IReader {
            +setFilePath(new_path)
            +read(): std::shared_ptr<DataTable>
        }

        class CsvReader {
            +setFilePath(new_path)
            +read(): std::shared_ptr<DataTable>
        }

        class XlsxReader {
            +setFilePath(new_path)
            +read(): std::shared_ptr<DataTable>
        }

        note "Many other readers not shown here" as N3
        N3 .. CsvReader
        N3 .. XlsxReader

        CsvReader -up-|> IReader
        XlsxReader -up-|> IReader
    }

    DataTable -- IDataTableProcessor
}


ReaderFactory --> IReader
WriterFactory --> IWriter
DataProcessorFactory --> IDataTableProcessor

SageParser --> DataProcessorFactory
SageParser --> WriterFactory
SageParser --> ReaderFactory
SageParser --> DataTable

@enduml
