@startuml

package ui {
    class SageParser
    {
        +init()
    }
}

package lib {
    class Table {
        -columnNames : vector<string>
        -dataRows : vector<Rows>
    }

    package Processors {
        class DataProcessorFactory
        {
            createDataProcessor(docType) : ITableProcessor
        }

        class ITableProcessor {
            +process(std::shared_ptr<Table>) : Table
        }

        class DefaultTableProcessor {
            +process(std::shared_ptr<Table>) : Table
        }

        class OmegaInvoiceProcessor {
            +process(std::shared_ptr<Table>) : Table
        }

        class BesuglayaInvoiceProcessor {
            +process(std::shared_ptr<Table>) : Table
        }

        note "Many other processors are not shown here" as N1
        N1 .. BesuglayaInvoiceProcessor
        N1 .. OmegaInvoiceProcessor

        DefaultTableProcessor -up-|> ITableProcessor
        BesuglayaInvoiceProcessor -up-|> DefaultTableProcessor
        OmegaInvoiceProcessor -up-|> DefaultTableProcessor
    }

    package Writers {

        class WriterFactory {
            createWriter(ReaderFileType) : IWriter
        } 

        interface IWriter {
            +setFilePath(new_path)
            +writeData(Table)
        }

        class CsvWriter {
            +setFilePath(new_path)
            +writeData(Table)
        }

        class XmlWriter {
            +setFilePath(new_path)
            +writeData(Table)
        }

        note "Many other writers not shown here" as N2
        N2 .. CsvWriter
        N2 .. XmlWriter

        CsvWriter -up-|> IWriter
        XmlWriter -up-|> IWriter
    }

    package Readers {
        class ReaderFactory {
            createReader(ReaderFileType) : IReader
        } 

        interface IReader {
            +setFilePath(new_path)
            +readData(): std::shared_ptr<Table>
        }

        class CsvReader {
            +setFilePath(new_path)
            +readData(): std::shared_ptr<Table>
        }

        class XlsxReader {
            +setFilePath(new_path)
            +readData(): std::shared_ptr<Table>
        }

        note "Many other readers not shown here" as N3
        N3 .. CsvReader
        N3 .. XlsxReader

        CsvReader -up-|> IReader
        XlsxReader -up-|> IReader
    }

    Table -- ITableProcessor
}


ReaderFactory --> IReader
WriterFactory --> IWriter
DataProcessorFactory --> ITableProcessor

SageParser --> DataProcessorFactory
SageParser --> WriterFactory
SageParser --> ReaderFactory
SageParser --> Table

@enduml
